if("overview"===document.body.dataset.title){var e=1,f=[{url:"https://digitalmediametrics.com/"},{url:"http://google.com/"},{url:"https://stackoverflow.com/"}],g=function(){var a=e;"true"===window.localStorage.getItem("linkListfirstVisit")&&(window.localStorage.setItem("linkListData",JSON.stringify(f)),window.localStorage.setItem("linkListfirstVisit","false"));var b=JSON.parse(window.localStorage.linkListData);a--;a=20*a;b=b.slice(a,a+20);for(var c=0;c<b.length;c++){var d=b[c],k=a,t=document.getElementById("link-list-container"),
h=document.createElement("div");h.classList.add("link-wrapper");h.innerHTML='<div class="link-list-item" data-id='+k+'>\n          <h3 class="link-number">'+(k+1)+'</h3>\n          <a href="'+d.url+'" class="link-url">'+d.url+'</a>\n          <div class="link-buttons">\n            <button type="button" class="link-buttons-btn btn-edit-link"><i class="fas fa-edit"></i></button>\n            <button type="button" class="link-buttons-btn btn-delete-link"><i class="fas fa-trash-alt"></i></button>\n          </div>\n        </div>';
t.append(h);a++}},l=function(){document.getElementById("link-list-container").innerHTML="";g()},m=function(){var a=JSON.parse(window.localStorage.linkListData);a=Math.ceil(a.length/20);document.getElementById("pagination-button-wrapper").innerHTML="";for(var b=0;b<a;b++){var c=b+1,d=document.createElement("button");c===e?d.innerHTML="<u>"+c+"</u>":d.textContent=c;d.classList.add("btn-pagination-number");d.classList.add("btn-pag");d.classList.add("btn");document.getElementById("pagination-button-wrapper").appendChild(d)}},
n=function(a){if("create"===a)var b=document.getElementById("create-link-input").value;else if("edit"===a)b=document.getElementById("edit-link-input").value;else return;if(""===b&&"create"===a){var c=document.getElementById("create-link-error-message");c.style.display="block";c.textContent="Please enter a valid URL, including http(s)://"}else""===b&&"edit"===a&&(c=document.getElementById("edit-link-error-message"),c.style.display="block",c.textContent="Please enter a valid URL, including http(s)://");
c=/^(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,}))\.?)(?::\d{2,5})?(?:[/?#]\S*)?$/i;if(c.test(b))return!0;c.test(b)||"create"!==
a?(a=document.getElementById("edit-link-error-message"),a.style.display="block",a.textContent="Please enter a valid URL, including http(s)://"):(a=document.getElementById("create-link-error-message"),a.style.display="block",a.textContent="Please enter a valid URL, including http(s)://");return!1};document.getElementById("create-link-form").addEventListener("submit",function(a){a.preventDefault();if(n("create")){a=document.getElementById("create-link-input").value;var b=JSON.parse(window.localStorage.linkListData);
b.push({url:a});window.localStorage.setItem("linkListData",JSON.stringify(b));window.location.href="results.html"}});document.addEventListener("click",function(a){if(a.target.classList.contains("btn-delete-link")||a.target.classList.contains("fa-trash-alt")){var b=0;a.target.classList.contains("btn-delete-link")?b=a.target.parentNode.parentNode.dataset.id:a.target.classList.contains("fa-trash-alt")&&(b=a.target.parentNode.parentNode.parentNode.dataset.id);var c=document.getElementById("delete-link-container-overlay");
c.style.display="block";a=JSON.parse(window.localStorage.linkListData);document.querySelector(".submitted-url-delete").innerHTML=""+a[b].url;document.getElementById("btn-delete-yes").addEventListener("click",function(){c.style.display="none";var d=JSON.parse(window.localStorage.linkListData);d.splice(b,1);window.localStorage.setItem("linkListData",JSON.stringify(d));1<e&&0===JSON.parse(window.localStorage.linkListData).length%20&&e--;l();m()});document.getElementById("btn-delete-no").addEventListener("click",
function(){c.style.display="none"})}});document.addEventListener("click",function(a){if(a.target.classList.contains("btn-edit-link")||a.target.classList.contains("fa-edit")){var b=0;a.target.classList.contains("btn-edit-link")?b=a.target.parentNode.parentNode.dataset.id:a.target.classList.contains("fa-edit")&&(b=a.target.parentNode.parentNode.parentNode.dataset.id);document.getElementById("edit-link-container-overlay").style.display="block";a=document.getElementById("edit-link-input");var c=JSON.parse(window.localStorage.linkListData);
a.value=c[b].url;document.getElementById("edit-link-form").setAttribute("data-id",b)}});var p=document.getElementById("edit-link-form");p.addEventListener("submit",function(a){a.preventDefault();if(n("edit")){a=document.getElementById("edit-link-input").value;var b=JSON.parse(window.localStorage.linkListData);b.splice(p.dataset.id,1,{url:a});window.localStorage.setItem("linkListData",JSON.stringify(b));l();q()}});var q=function(){document.getElementById("edit-link-container-overlay").style.display=
"none";document.getElementById("edit-link-error-message").innerHTML=""};document.getElementById("btn-cancel-edit-link").addEventListener("click",q);window.addEventListener("click",function(a){a.target.matches(".btn-pagination-number")&&(e=Number(a.target.textContent),document.getElementById("create-link-error-message").innerText="",l(),m())});document.getElementById("btn-previous-page").addEventListener("click",function(){1!==e&&(e--,l(),m())});document.getElementById("btn-next-page").addEventListener("click",
function(){var a=JSON.parse(window.localStorage.linkListData);e!==Math.ceil(a.length/20)&&(e++,l(),m())});"false"!==window.localStorage.linkListfirstVisit&&(window.localStorage.linkListfirstVisit?window.localStorage.setItem("linkListfirstVisit","false"):window.localStorage.setItem("linkListfirstVisit","true"));g();m()};if("results"===document.body.dataset.title&&document.getElementById("submission-container")){var r=JSON.parse(window.localStorage.linkListData);document.querySelector(".submitted-url").textContent=""+r[r.length-1].url};
